version: "3.7" # Omitting the verison or higher versions seam not to be  supported by testcontainers yet
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: someUser
      POSTGRES_PASSWORD: somePw
      POSTGRES_DB: someDb
    ports:
      - 5432:5432
  mockserver:
    image: mockserver/mockserver:mockserver-5.11.2
    ports:
      - 1080:1080
