spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/someDb
    password: somePw
    username: someUser
  jpa:
    #    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
myConfig:
  holidayApiUrl: https://feiertage-api.de
